AWSTemplateFormatVersion: '2010-09-09'

Description: Create S3 bucket, SQS queue, and EC2 instance with unique suffix
 
Parameters:
  UniqueSuffix:
    Type: String
    Description: Unique suffix for resource names
 
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "hhhhh-bucket-${UniqueSuffix}"
  MySQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "hhhhh-queue-${UniqueSuffix}"
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-03bb6d83c60fc5f7c  # ✅ Valid AMI for ap-south-1
      InstanceType: t2.micro
     
